# Generated by Django 4.1 on 2022-09-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('publisher', models.CharField(max_length=200)),
            ],
        ),
    ]
