# Generated by Django 4.1 on 2022-08-22 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0002_rename_date_posts_current_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='comments',
        ),
    ]
