# Generated by Django 4.0.6 on 2022-08-09 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapi', '0002_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='rating',
        ),
    ]
